# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OverlayMaker
                                 A QGIS plugin
 Creates overlays
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-16
        copyright            : (C) 2026 by Anna Keener
        email                : annahkeener@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OverlayMaker class from file OverlayMaker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .overlay_maker import OverlayMaker
    return OverlayMaker(iface)
