# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OverlayMaker
                                 A QGIS plugin
 Creates overlays
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-01-16
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Anna Keener
        email                : annahkeener@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject, QgsMapLayer
from PyQt5.QtWidgets import QComboBox, QPushButton
from PyQt5 import QtWidgets, QtCore

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .overlay_maker_dialog import OverlayMakerDialog
import os.path

#import all of the functions I've written
from . import model

class OverlayMaker:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """


        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'OverlayMaker_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        #current Mode (MY CODE)
        self.mode = ''

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Overlay Maker')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('OverlayMaker', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/overlay_maker/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Overlay Maker'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&Overlay Maker'),
                action)
            self.iface.removeToolBarIcon(action)

    #------MY CODE STARTS HERE-----------

    #View :)-------------------------

    def showMainPage(self):
        self.dlg.currentDisplay.setCurrentIndex(0)
    
    def clearInputs(self):
        #Find all comboboxes
        all_combos = self.dlg.findChildren(QComboBox)
        #and clear them all
        for combo in all_combos:
            combo.clear()

    def pickFile(self, textBox, type):
        """Opens a file dialog for the user to select a file."""
        qfd = QtWidgets.QFileDialog()

        title = "Select a file"

        

        if type == "folder":
            filePath = QtWidgets.QFileDialog.getExistingDirectory(qfd, "Select Folder", "C:\\")
            textBox.setText(filePath)
    
        elif type == "SHP":
             # Define file filters (e.g., Shapefiles)
            f = "Shapefiles (*.shp)"
            filePath, _filt = QtWidgets.QFileDialog.getOpenFileName(qfd, title, ".", f)
            textBox.setEditable(True)
            textBox.setCurrentText(filePath)
        
        elif type == "DEM":
            f = "TIF Files (*.tif *.tiff)"
            filePath, _filt = QtWidgets.QFileDialog.getOpenFileName(qfd, title, ".", f)
            textBox.setEditable(True)
            textBox.setCurrentText(filePath)

        


    def activateMode(self, button, mode = str):
        self.dlg.currentDisplay.setCurrentIndex(0)
        self.dlg.AOButton.setCheckable(True)

        layers = QgsProject.instance().mapLayers()
        dems = ['']
        vectors = ['']

         #collecting all dems currently loaded
        for id, l in layers.items():
            if l.type() == QgsMapLayer.RasterLayer:
                dems.append(l.name())
            elif l.type() == QgsMapLayer.VectorLayer:
                vectors.append(l.name())

        if mode == "AO":
            self.mode = "AO"
            self.dlg.modePage.setCurrentIndex(0)
            self.dlg.AOdem.addItems(dems)
            self.dlg.AOBlocks.addItems(vectors)
        elif mode == "RS":
            self.mode = "RS"
            self.dlg.modePage.setCurrentIndex(2)
            self.dlg.RSdem.addItems(dems)
            self.dlg.RSWT.addItems(dems)
        elif mode == "GH":
            self.mode = "GH"
            self.dlg.modePage.setCurrentIndex(1)
            self.dlg.GHdem.addItems(dems)
            self.dlg.GHBlocks.addItems(vectors)
        elif mode == "RR":
            self.mode = "RR"
            self.dlg.modePage.setCurrentIndex(3)
            self.dlg.RROverlay.addItems(dems)
            self.dlg.RRRoads.addItems(vectors)

    def onSubmit(self, mode):
        print("CONSTRUCT")
        if self.mode == "AO":
            model.autoOverlay(self.dlg.AOBlocks.currentText(), self.dlg.AOdem.currentText(), self.dlg.AOOutput.text())
        elif self.mode == "RS":
            model.rasterSubtractor(self.dlg.RSdem.currentText(), self.dlg.RSWT.currentText(), self.dlg.RSOutput.text())
        elif self.mode == "RR":
            model.roadRaisingLength(self.dlg.RRRoads.currentText(), self.dlg.RROverlay.currentText(), self.dlg.RROutput.text())
        elif self.mode == "GH":
            model.rasterHist(self.dlg.GHOverlay.currentText(), self.dlg.GHBlocks.currentText(), None, self.dlg.GHOutput.text(), None, "Histogram")

    
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = OverlayMakerDialog()
                    
        
        #------MY CODE STARTS HERE-----------

        #reset progress bar
        self.dlg.progressBar.setValue(0)
        #set page to start page
        self.dlg.currentDisplay.setCurrentIndex(1)

        #----------------------------------------Controller------------------------------------------

        self.dlg.AOButton.clicked.connect(lambda: self.activateMode(self.dlg.AOButton, "AO"))
        self.dlg.AOSelectBlocks.clicked.connect(lambda: self.pickFile(self.dlg.AOBlocks, "SHP"))
        self.dlg.AOSelectDEM.clicked.connect(lambda: self.pickFile(self.dlg.AOdem, "DEM"))
        self.dlg.AOSelectOP.clicked.connect(lambda: self.pickFile(self.dlg.AOOutput, "folder"))

        self.dlg.RSButton.clicked.connect(lambda: self.activateMode("RS"))
        self.dlg.RSSelectWT.clicked.connect(lambda: self.pickFile(self.dlg.RSWT, "DEM"))
        self.dlg.RSSelectDEM.clicked.connect(lambda: self.pickFile(self.dlg.RSDEM, "DEM"))
        self.dlg.RSSelectOutput.clicked.connect(lambda: self.pickFile(self.dlg.RSOutput, "folder"))

        self.dlg.RRButton.clicked.connect(lambda: self.activateMode("RR"))
        self.dlg.RRSelectOverlay.clicked.connect(lambda: self.pickFile(self.dlg.RROverlay, "DEM"))
        self.dlg.RRSelectRoads.clicked.connect(lambda: self.pickFile(self.dlg.RRRoads, "SHP"))
        self.dlg.RRSelectOutput.clicked.connect(lambda: self.pickFile(self.dlg.RROutput, "folder"))

        self.dlg.GHButton.clicked.connect(lambda: self.activateMode("GH"))
        self.dlg.GHSelectOverlay.clicked.connect(lambda: self.pickFile(self.dlg.GHdem, "DEM"))
        self.dlg.GHSelectBlocks.clicked.connect(lambda: self.pickFile(self.dlg.GHBlocks, "SHP"))
        self.dlg.GHSelectOutput.clicked.connect(lambda: self.pickFile(self.dlg.GHOutput, "folder"))

        self.dlg.pushButton.clicked.connect(lambda: self.onSubmit(self.mode))

        #------MY CODE ENDS HERE-----------

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            
            pass
